server:
  port: 8089

eureka:
  instance:
    hostname: server2
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://server1:8088/eureka/

spring:
 profiles: server2